import type { ReactElement, ReactNode } from 'react';
import type { StyleProp, TextStyle, ViewStyle } from 'react-native';

/** Permitted toast variants for built-in styling. */
export type ToastType = 'success' | 'error' | 'info' | 'warning';

/** Placement for the toast stack within the viewport. */
export type ToastPlacement = 'top' | 'bottom';

/** Horizontal alignment for toast cards. */
export type ToastHorizontalPosition = 'left' | 'center' | 'right';

/**
 * Haptic feedback intensities. `false` disables feedback entirely. Used by
 * both per-toast `hapticFeedback` and global `accessibility.hapticFeedback`.
 */
export type HapticFeedback =
  | false
  | 'light'
  | 'medium'
  | 'heavy'
  | 'success'
  | 'warning'
  | 'error';

/**
 * Combined position controls. `vertical` defaults to the legacy `placement`,
 * while `horizontal` enables aligning the stack left/right/center.
 */
export interface ToastPosition {
  vertical?: ToastPlacement;
  horizontal?: ToastHorizontalPosition;
}

/** Signature for easing functions used by react-native Animated. */
export type ToastEasingFunction = (value: number) => number;

/**
 * Shape of a toast message managed by the provider.
 * Optional properties extend customisation without breaking existing usage.
 *
 * Accessibility: All text content is announced to screen readers. Use `accessibilityLabel`
 * and `accessibilityHint` to provide additional context for users of assistive technology.
 */
export interface ToastMessage {
  /** Unique identifier generated by the provider. */
  id: string;
  /** Type controls background colour through the active config. Defaults to `info`. */
  type?: ToastType;
  /** Optional heading displayed above the message body. */
  title?: string;
  /** Core message presented to the user. */
  message: string;
  /** Optional React element rendered before the text, such as an icon. */
  icon?: ReactNode;
  /** Override the auto-dismiss timeout for this message only. */
  duration?: number;
  /** Optional press handler called before the toast dismiss animation runs. */
  onPress?: () => void;
  /** Per-toast style override for the card wrapper. */
  style?: StyleProp<ViewStyle>;
  /** Per-toast background color override. */
  backgroundColor?: string;
  /** Per-toast border radius override (in pixels). */
  borderRadius?: number;
  /** Per-toast padding override. */
  padding?: {
    vertical?: number;
    horizontal?: number;
  };
  /** Per-toast font size override for message text (in pixels). */
  messageFontSize?: number;
  /** Per-toast font size override for title text (in pixels). */
  titleFontSize?: number;

  // Accessibility Properties
  /**
   * Custom accessibility label for screen readers. If omitted, generated
   * automatically from `title` + `message` (capped at 150 chars).
   */
  accessibilityLabel?: string;

  /**
   * Additional context spoken after the label. Defaults to a type-specific
   * hint, optionally followed by "Double tap to dismiss" when interactive.
   */
  accessibilityHint?: string;

  /**
   * Honor the device's font-scaling accessibility setting. Default: `false`.
   * Recommended `true` for WCAG 2.1 SC 1.4.4 compliance.
   */
  allowFontScaling?: boolean;

  /**
   * Maximum number of lines for the message. Default: `2`. `0` for unlimited.
   * Screen-reader output is never truncated.
   */
  messageMaxLines?: number;

  /**
   * Haptic feedback fired when the toast is pressed. Default: disabled.
   * See {@link HapticFeedback} for available intensities.
   */
  hapticFeedback?: HapticFeedback;
}

/**
 * Runtime configuration merged into a single object stored in context.
 * Consumers can update values via {@link ToastApi.setToastConfig}.
 *
 * Accessibility: Configuration supports screen readers, high contrast,
 * and respects device accessibility settings. See `accessibility` section below.
 */
export interface ToastConfig {
  /** Typography customisation for built-in toast layout. */
  font?: {
    fontFamilyRegular?: string | null;
    fontFamilyBold?: string | null;
    /** Font size for the toast message text (default: 14). */
    messageFontSize?: number;
    /** Font size for the toast title text (default: 16). */
    titleFontSize?: number;
  };
  /** Background colours for each toast variant. */
  bgColor: Record<ToastType, string>;
  /** Global auto-dismiss duration in milliseconds. */
  timeToDismiss: number;
  /** Gap between stacked toasts (default: 12). */
  spacing?: number;
  /** Position of the toast stack (default: bottom). */
  placement?: ToastPlacement;
  /** Horizontal alignment for the toast stack (default: center). */
  horizontalPosition?: ToastHorizontalPosition;
  /** Full position override combining vertical and horizontal preferences. */
  position?: ToastPosition;
  /** Additional offset applied on top of the safe-area inset. */
  offset?: number;
  /** Animation tuning parameters for enter/exit transitions. */
  animation?: {
    /** Initial translation distance in pixels. */
    initialTranslation?: number;
    /** Duration of the entrance animation in milliseconds. */
    appearDuration?: number;
    /** Duration of the exit animation in milliseconds. */
    disappearDuration?: number;
    /** Easing function applied to both animations. */
    easing?: ToastEasingFunction;
  };
  /** Global border radius for toast cards (default: 12). */
  borderRadius?: number;
  /** Global padding for toast cards. */
  padding?: {
    vertical?: number;
    horizontal?: number;
  };
  /** Global horizontal margin for toast cards (default: 16). Only applies to top/bottom positions. */
  marginHorizontal?: number;
  /** Shadow customization for toast cards. */
  shadow?: {
    color?: string;
    opacity?: number;
    offset?: { width: number; height: number };
    radius?: number;
  };
  /**
   * Allows overriding the default wrapper styling used by the built-in toast card.
   * Applied in addition to the base style.
   */
  toastStyle?: StyleProp<ViewStyle>;
  /** Additional style for the toast title text. */
  titleStyle?: StyleProp<TextStyle>;
  /** Additional style for the toast message text. */
  messageStyle?: StyleProp<TextStyle>;
  /**
   * Provide a render hook to replace the default toast component.
   * Receives the generated default toast so consumers can reuse parts of it.
   */
  renderToast?: (options: {
    message: ToastMessage;
    index: number;
    defaultToast: ReactElement;
  }) => ReactElement;

  // Accessibility Configuration
  /**
   * Global accessibility settings for all toasts. Per-toast values override
   * these defaults.
   */
  accessibility?: {
    /** Honor the device font-scaling preference (WCAG 1.4.4). Default: `false`. */
    allowFontScaling?: boolean;

    /** Default `messageMaxLines` for every toast. Default: `2`. */
    messageMaxLines?: number;

    /** Default {@link HapticFeedback} intensity. Default: disabled. */
    hapticFeedback?: HapticFeedback;

    /**
     * Optional text colors per toast type for advanced contrast tooling.
     * Accepts an `[r, g, b]` tuple or `#RRGGBB` string.
     */
    textColors?: Partial<Record<ToastType, [number, number, number] | string>>;

    /**
     * Whether toasts auto-announce via `accessibilityLiveRegion` on appear.
     * Default: `true`.
     */
    announceOnAppear?: boolean;

    /**
     * Override the `accessibilityRole` for each toast type. Falls back to a
     * Pressable-supported role (`button`).
     */
    roleMap?: Partial<Record<ToastType, string>>;
  };

  /**
   * Maximum simultaneously visible toasts. Default: 5.
   * When exceeded, behaviour is controlled by {@link overflow}.
   * Set to `Infinity` to disable the cap (matches v3 behaviour).
   */
  maxVisible?: number;

  /**
   * Behaviour when {@link maxVisible} is exceeded.
   * - `'evict'` (default): drop the oldest toast with a fast exit.
   * - `'queue'`: keep the new toast pending until a slot frees up.
   */
  overflow?: 'evict' | 'queue';

  /**
   * Stagger between simultaneous toast entrance animations, in ms.
   * Default: 30. Each toast schedules its enter animation with `delay = index * staggerMs`.
   */
  staggerMs?: number;

  /**
   * When true (default), bottom-placed toasts auto-flip to top when they would
   * obscure a currently focused input field. Implements WCAG 2.2 SC 2.4.11.
   */
  respectFocus?: boolean;

  /**
   * Disable auto-dismiss globally. Useful for accessibility flows where users
   * always dismiss manually. Default: false.
   */
  disableAutoDismiss?: boolean;

  /**
   * Opt-in palette tweaks for higher contrast (WCAG 2.2 1.4.6 friendly).
   * Default: false.
   */
  highContrast?: boolean;

  /**
   * Enable swipe-to-dismiss as an additive gesture. Tap-to-dismiss is always available.
   * Implemented with React Native's built-in `PanResponder` (no extra peer deps).
   * Default: false.
   */
  swipeToDismiss?: boolean;
}

/**
 * Public API returned from {@link useToast} and exposed on the imperative
 * `toast` facade. The v3 names (`addToast`, `removeToast`, `setToastConfig`)
 * are preserved verbatim; `show`, `dismiss`, and `configure` are aliases.
 */
export interface ToastApi {
  /** Push a new toast into the stack. */
  addToast(message: Omit<ToastMessage, 'id'>): string;
  /** Alias of {@link addToast}. */
  show(message: Omit<ToastMessage, 'id'>): string;
  /** Remove a toast by id, or fall back to the most recent toast. */
  removeToast(id?: string): void;
  /** Alias of {@link removeToast}. */
  dismiss(id?: string): void;
  /** Remove all toasts immediately. */
  clear(): void;
  /** Merge new configuration values with the current global config. */
  setToastConfig(config: Partial<ToastConfig>): void;
  /** Alias of {@link setToastConfig}. */
  configure(config: Partial<ToastConfig>): void;
  /** Convenience helpers for common types. */
  success(message: string | Omit<ToastMessage, 'id' | 'type'>): string;
  error(message: string | Omit<ToastMessage, 'id' | 'type'>): string;
  warning(message: string | Omit<ToastMessage, 'id' | 'type'>): string;
  info(message: string | Omit<ToastMessage, 'id' | 'type'>): string;
}

/** Props accepted by the {@link Toaster} component. */
export interface ToasterProps {
  /** Optional configuration applied on mount and merged into the global config. */
  config?: Partial<ToastConfig>;
  /**
   * Children are not required: `<Toaster />` is a sibling, not a wrapper.
   * Accepted for the rare case of nesting it inside layout, but renders nothing.
   */
  children?: ReactNode;
}
